name: ceesam_app
description: Mobile Application for service feedback collection for CESAAM.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.5
  google_fonts: ^3.0.1
  flutter_rating_bar: ^4.0.1
  webview_flutter: ^3.0.4
  url_launcher: ^6.1.6
  google_maps_flutter: ^2.2.1
  flutter_spinkit: ^5.1.0
  dots_indicator: ^2.1.0
  emojis: ^0.9.9
  provider: ^6.0.5
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.9

flutter_native_splash:
  color: "#1C623B"
  image: assets/png_images/CESAAM_LOGO_1000.png
  color_dark: "#000000"
  android: true

flutter:
  uses-material-design: true
  assets:
    - assets/png_images/
    - assets/svg_images/
